### ISSUE TITLE
Hangs at indeterminate times

### ISSUE THREAD

**Issue by roytruelove** [zklhp/emacs-w64#1]
Periodically the app becomes unresponsive, once an hour or so.  The only way I've found to recover is to Kill the app in the Resource Manager.

I am able to replicate it pretty consistently by using the [undo tree](https://www.emacswiki.org/emacs/UndoTree) plugin, however it's also happened when using basic `org-mode` commands.

Unfortunately I'm not skilled enough in Windows to know how to provide debugging information for you; if you're able to provide / point me to some resources that describe how to do so then I'll forward it along.

Thank you!
-Roy

```
System Info:

emacs:  25.0.94.2
Windows 10 Home : v1607
OS Build : 14393.51
Processor : Intel i7-6700HQ
Ram: 8g
```

**Comment by zklhp** [comment]
Hi Roy,
I’m afraid I can’t help. To workaround this problem you may try the official version at

http://ftpmirror.gnu.org/emacs/windows/

or the pretests at

http://alpha.gnu.org/gnu/emacs/pretest/windows/

and find whether the hang is gone.

The following are my guesses:
- The hang may relate to my build. Thus you should try the official one.
- The hang may relate to the settings or the packages. You can try `emacs -Q` or `emacs -Q -l /path/to/el.el`. Also check the hooks (`F1 v org-mode-hook RET`) and timers (`F1 v timer-list RET`)
- The hang may relate to your environment. A anti-virus software, a misconfigured setting, or a system problem.

Sorry,

Chris

**Comment by roytruelove** [comment]
Thanks Chris.

For clarity can I ask what this repo is used for?  It seems to be a straightup fork (actually copy) of the emacs repo with no proprietary changes.

I'm asking because people might be confused by its existence and be looking to you to deal with issues.  You might consider removing the 'Issues' section from this repo or perhaps extend the README to explain your role in this project, so that you don't get harrassed with issues from people like me 😀

**Comment by zklhp** [comment]
Hello Roy,
While it is truly a fork, I don’t want to remove the Issues section. Because I really want to help people work out, whether they use my emacs-w64 or not. Emacs is so famous that people should understand that this is just a place for storing the source code and providing the binary packages, I think. And there is another reason for keeping the Issues section: I can’t login the SourceForge where [the old Emacs-w64 project](https://sourceforge.net/projects/emacsbinw64/) is on, so I want a place to talk with the users of Emacs-w64. But maybe changing the README is a good idea. I’m thinking how to change the README without changing the source code. By adding a new branch?

In end, I’m not get harassed with your issue. I really hope I could help.

Happy Hacking,

Chris
