### ISSUE TITLE
Emacs 25.3 out

### ISSUE THREAD

**Issue by seagle0128** [zklhp/emacs-w64#5]
Hi, can you please build w64 binary for GNU Emacs 25.3, which includes a severe vulnerability. Thanks!

**Comment by zklhp** [comment]
Done. See

https://github.com/zklhp/emacs-w64/releases/tag/e0284ab

I was wondering how many people are still using this version, as the official one is better than this. Nevertheless, I will keep up.

Thank you.

**Comment by jdtw** [comment]
@zklhp -- I'm curious, what do you mean by the official one is better than this? I use this version for the JPEG, GIF, PNG, TIFF, SVG, XML2, and GnuTLS support.

**Comment by zklhp** [comment]
The official version supports the functions that you mentioned. The implementation is the same as mine, where it has a [emacs-25-x86_64-deps.zip](https://ftp.gnu.org/gnu/emacs/windows/emacs-25-x86_64-deps.zip) that contains the necessary DLL files.

The shortcoming of Emacs-w64 is that some support is broken, such as ImageMagick.

**Comment by seagle0128** [comment]
@zklhp does it mean you recommend to use the official builds with emacs-25-x86_64-deps.zip? There is no official build for 25.3 on the FTP so far.

**Comment by zklhp** [comment]
@seagle0128

By now you may use Emacs-w64. And please don’t use Emacs-w64 with emacs-25-x86_64-deps.zip. That may lead to chaos. There will have 25.3 on the official FTP shortly, I guess. I said the official version is better because I want to tell you the truth 😢 . But it doesn’t mean that it will be made in time, which is an advantage of this build.

Thanks.

**Comment by seagle0128** [comment]
@zklhp  Sure. Thanks for the reply!
